name: Deploy to Surge

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        name: Deploying to surge
        steps:
            - uses: actions/checkout@v1
            - name: Install Surge
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm install -g surge

            - name: Install Packages
              run: npm install

            - name: Build Project
              run: npm run build

            - name: Deploy Project
              run: surge ./dist ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
